(defvar *eksempelstring* "Bilder: file=\"Mine Bilder/\\\"reapers\\\".png\".")

(defvar *escape-map* (produce-standard-escape-map))
(defun produce-standard-escape-map ()
  (let ((escape-map (make-hash-table :test 'equal)))
    (dolist (pair '((#\" #\")
		    (#\n #\Newline)
		    (#\t #\Tab)
		    (#\r #\Return)))
      (setf (gethash (car pair) escape-map) (cadr pair)))
    escape-map))

(defun get-escaped-char (char)
  (gethash char *escape-map*))

(defvar *whitespace* '(#\Space #\Return #\Newline #\Tab #\No-Break_Space))
(defvar *stop-symbols* '(#\.)))

(defun tokenise (string)
  (let ((inside-literal nil)
	(acc ())
	(tegn #\Space)
	(tokens ())
	;; should be defined outside function so that they may be set from the outside (IOC, etc.)
    (flet ((empty-acc ()
	     (when (not (equal () acc))
	       (push (concatenate 'string (reverse acc)) tokens)
	       (setf acc ())))
	   (add-char (char)
	     (push char acc))
	   (cross-literal-boundary ()
	     (setf inside-literal (not inside-literal)))
	   (whitespacep ()
	     (member tegn *whitespace*))
	   (stop-symbolp ()
	     (member tegn *stop-symbols*)))
      (dotimes (i (length string))
	(setf tegn (char string i))
	(cond ((equal #\" tegn)
	       (add-char tegn)
	       (cross-literal-boundary))
	      ((and (whitespacep) (not inside-literal))
	       (empty-acc))
	      ((and (stop-symbolp) (not inside-literal))
	       (empty-acc) (add-char tegn) (empty-acc))
	      ((and (equal #\\ tegn) inside-literal)
	       (add-char (get-escaped-char (char string (1+ i))))
	       (incf i))
	      ('ELSE (add-char tegn))))
      (empty-acc)
      (reverse tokens))))

	
